### ISSUE TITLE
normalizeUrl() doesn't handle certain valid URLs

### ISSUE THREAD

**Issue by jancurn** [apify/apify-shared-js#14]
For example, URLs with escaped or diacritic chars that work normally in browser.

**Comment by jancurn** [comment]
Also, we should expose this function in `Apify.utils`.

**Comment by B4nan** [comment]
Closing as this is probably no longer valid, as I've recently refactored the `normalizeUrl` to use the native `URL` object, so parsing should be more aligned with how browsers work.
