### ISSUE TITLE
“create actor from task” does not correctly escape characters in the input fields

### ISSUE THREAD

**Issue by katacek** [apify/apify-shared-js#356]
The problem is probably in `utilities.ts` -> `makeInputJsFieldsReadable()` in the part below but I was not able to fix it quickly...

```
const replacementValue = isSingleFunction
            ? maybeFunction.replace(/[;]+$/g, '') // Remove trailing semicolons
            : `\`${maybeFunction}\``;
```

Reported on [Slack](https://apifier.slack.com/archives/C0L33UM7Z/p1674117975989509), prnt scrn below

<img width="630" alt="CleanShot 2023-01-19 at 09 46 37@2x" src="https://user-images.githubusercontent.com/56041262/213714398-05dd6d52-3491-4f69-a749-e2cf570ea52b.png">
<img width="371" alt="CleanShot 2023-01-19 at 09 45 20@2x" src="https://user-images.githubusercontent.com/56041262/213714411-a1567a5e-50aa-4319-89c8-edbace84b038.png">

**Comment by gippy** [comment]
The functionality will be removed: https://github.com/apify/apify-core/issues/17471
