### ISSUE TITLE
'ENV_VARS' incorrectly imported in logger

### ISSUE THREAD

**Issue by FilipRazek** [apify/apify-shared-js#358]
When using [apify-client](https://github.com/apify/apify-client-js) with [netlify](https://github.com/netlify/cli), I ran into an error due to imports in `@apify/log`:

```
ERROR in ../node_modules/@apify/log/index.mjs 146:29-37
Can't import the named export 'ENV_VARS' from non EcmaScript module (only default export is available)
 @ ../node_modules/apify-client/dist/apify_client.js
 @ ../node_modules/apify-client/dist/index.js
 @ ../node_modules/apify-client/dist/index.mjs
```

`@apify/log/index.mjs` seems to be importing the environment variables from `node_modules/@apify/consts/index.js`, which contains this:
```
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
ENV_VARS,
...
}
```

Removing the `0 &&` works as a dirty fix, but the expected behavior is probably to import from `node_modules/@apify/consts/index.js`, from which ENV_VARS are correctly exported.

I haven't been able to identify if this was a build issue or a configuration mistake on my part.

**Comment by B4nan** [comment]
Can you provide a reproduction for this (without using netlify so we know it's not something specific to their runtime)? `@apify/log` works fine in ESM projects, we use that on daily basis. Also tried to do this in an ESM project, works fine locally:

```ts
import { ApifyClient } from "apify-client";

const c = new ApifyClient();
console.log(c);
```

We use https://github.com/addaleax/gen-esm-wrapper for the ESM support and I can see there is a new version, including some fix for default exports (https://github.com/addaleax/gen-esm-wrapper/pull/8), so maybe updating that and rebuilding could help.

FYI we want to gradually move to native ESM with most of our packages later this year, including the client most probably.

**Comment by B4nan** [comment]
I will close this as it's not reproducible, will be happy to reopen with a failing repro.
