### ISSUE TITLE
Use a different url slug package

### ISSUE THREAD

**Issue by pownkel** [apify/apify-shared-js#76]
My team recently started using apify-js for crawling, and our open source license detection tool gave an unknown license alert for this package's dependency on [slugg ](https://www.npmjs.com/package/slugg). After a look at the slugg repo, they don't have a license file at all, and the repo hasn't been maintained in quite some time.

Since it looks like slugg is only used in one place in apify-shared, would it be possible to replace it with a different package that has similar functionality, like [slugify ](https://www.npmjs.com/package/@sindresorhus/slugify) or [url-slug](https://www.npmjs.com/package/url-slug)? I'd be willing to submit that PR myself if necessary.

**Comment by mnmkng** [comment]
Hi @pownkel, we're happy that you chose our SDK for crawling. We reviewed the problematic function and it seems that we can safely remove it from this package. I'll release `apify-js` with the updated package soon.
